apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reference-service
  description: Knowledge Management Search service
  tags:
    - java
    - test
  annotations:
    backstage.io/kubernetes-label-selector: app=knowledge-management-search-service,component=search
spec:
  type: service
  lifecycle: experimental
  owner: platform-acceleration
  system: csp
  children: []
