apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: reference-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/referenceservice
  backstage.io/source-location: url:https://github.service.anz/csp/referenceservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: platform-acceleration
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: audit-service
 description: Audit Service
 annotations:
  github.com/project-slug: csp/auditservice
  backstage.io/source-location: url:https://github.service.anz/csp/auditservice
  jira/project-key: CSPPS
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: platform-acceleration
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: feature-toggle-services
 description: test-desc

 annotations:
  github.com/project-slug: csp/featuretoggleservice
  backstage.io/source-location: url:https://github.service.anz/csp/featuretoggleservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: business-banker-desktop
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: comment-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/commentsservice
  backstage.io/source-location: url:https://github.service.anz/csp/commentservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: business-banker-desktop
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: shoppingcarte
 description: test-desc

 annotations:
  github.com/project-slug: csp/shoppingcart
  backstage.io/source-location: url:https://github.service.anz/csp/shoppingcart
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: aryabhata-squad
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: address-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/addressservice
  backstage.io/source-location: url:https://github.service.anz/csp/addressservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: discovery-banker-desktop-personal-loan-banker-desktop
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: docvault-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/documentvault-api
  backstage.io/source-location: url:https://github.service.anz/csp/documentvault-api
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: asterix
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: product-service-v1
 description: test-desc

 annotations:
  github.com/project-slug: csp/productservice-v1
  backstage.io/source-location: url:https://github.service.anz/csp/productservice-v1
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: wukong-chengdu
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: consent-management-ui
 description: test-desc

 annotations:
  github.com/project-slug: csp/consent-ui
  backstage.io/source-location: url:https://github.service.anz/csp/consent-ui
 tags:
   - react-js
   - ui
spec:
 type: service
 lifecycle: production
 owner: wukong-chengdu
 system: csp

---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: consent-management-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/consent-service
  backstage.io/source-location: url:https://github.service.anz/csp/consentservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: wukong-chengdu
 system: csp

 ---
apiVersion: backstage/io/v1alpha1
kind: Component
metadata: 
 name: customer-service-v2
 description: test-desc

 annotations:
  github.com/project-slug: csp/customerservicev2
  backstage.io/source-location: url:https://github.service.anz/csp/customerservicev2
  backstage.io/kubernetes-label-selector: 'app=customer-service-v2'
 tags:
   - java
 links: 
   -url: https://confluence.service.anz/display/BEX/CSP+Customer+Service
    title: Solution Architecture
    icon: document 
spec:
 type: service
 lifecycle: production
 owner: bds
 system: csp
 providesApis:
   - customer-service-v2-api
 consumesApis:
   - party-service-api
 dependsOn:
   [
     "resource:customer-history-db"
     "component:feature-toggle-services"
     "component:party-service"
   ] 

---
apiVersion: backstage/io/v1alpha1
kind: API
metadata: 
 name: customer-service-v2-api
 description: test-desc

 annotations:
  github.com/project-slug: csp/customerservicev2
  backstage.io/source-location: url:https://github.service.anz/csp/customerservicev2
  backstage.io/techdocs-ref: https://github.service.anz/bhradwad/customerservicev2/tree/develop
 tags:
   - java
 links: 
   -url: https://confluence.service.anz/display/BEX/CSP+Customer+Service
    title: Solution Architecture
    icon: document 
spec:
 type: openapi
 lifecycle: production
 owner: bds
 system: csp
 definition:
    $text: https://github.service.anz.bhradwad/customerservicev2/blob/develop/web/src/main/resources/interfaces/swagger/swagger_definition/Customer%20Service.yaml
