apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knowledge-management-search-service
  description: Knowledge Management Search service
  tags:
    - java
    - search
  annotations:
    backstage.io/kubernetes-label-selector: app=knowledge-management-search-service,component=search
spec:
  type: service
  lifecycle: experimental
  owner: knowledge-management
  system: knowledge-management
  children: []
