apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: reference-service
 description: test-desc
 annotations:
  github.com/project-slug: csp/referenceservice
  backstage.io/source-location: url:https://test.com/csp/referenceservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: platform-acceleration
 system: csp

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: audit-service
 description: Audit Service
 annotations:
  github.com/project-slug: csp/auditservice
  backstage.io/source-location: url:https://test.com/csp/auditservice
  jira/project-key: CSPPS
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: platform-acceleration
 system: csp

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: feature-toggle-services
 description: test-desc
 annotations:
  github.com/project-slug: csp/featuretoggleservice
  backstage.io/source-location: url:https://test.com/csp/featuretoggleservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: business-banker-desktop
 system: csp

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: comment-service
 description: test-desc
 annotations:
  github.com/project-slug: csp/commentsservice
  backstage.io/source-location: url:https://test.com/csp/commentservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: business-banker-desktop
 system: csp

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: shoppingcarte
 description: test-desc
 annotations:
  github.com/project-slug: csp/shoppingcart
  backstage.io/source-location: url:https://test.com/csp/shoppingcart
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: aryabhata-squad
 system: csp
 children: ['feature-toggle-services','address-service']

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: address-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/addressservice
  backstage.io/source-location: url:https://test.com/csp/addressservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: discovery-banker-desktop-personal-loan-banker-desktop
 system: csp
