apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
 name: reference-service
 description: test-desc

 annotations:
  github.com/project-slug: csp/referenceservice
  backstage.io/source-location: url:https://test.com/csp/referenceservice
 tags:
   - java
spec:
 type: service
 lifecycle: production
 owner: platform-acceleration
 system: csp
